# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4af5d8627b783d786e8bbcddd2763c34f1799a2816d32906ec998e17eedf77685eacf03f34bd0116ae0c662869c8c5870e47492481d0f175501ae43efae3fed3

test:
  secret_key_base: 57d4716db8ebb6cffe8c4693079558cf118f668a38ae89b72ddd6b2891bb29868a13b2be28813a1801776dca2737ba0a9c32e6b50829fe46deabd8bb53bd25a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
